# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5ca24dd
_src_path: ../ssl_py_template
author_email: jesbauti20@gmail.com
author_name: Jesús Bautista Villar
description: A Qt-based visualization app
include_docs: true
include_examples: true
license: MIT
package_name: ssl_vista
project_name: ssl_vista
repo_url: https://gitea.lyapunov.local/Swarm-Systems-Lab/ssl_simulator_vista
use_docker: true
